/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.CTHDBUS;
import java.util.logging.Level;
import java.util.logging.Logger;
import Tools.ThongBao;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class CHITIETHOADON extends javax.swing.JFrame {

    EMPLOYEE eBUS = new EMPLOYEE();
    CTHDBUS ctBUS = new CTHDBUS();

    public CHITIETHOADON()  {
        try {
            initComponents();
            jTextFieldmacthd.setEnabled(false);
            jTextFieldmahd.setEnabled(false);
            eBUS.sach();
        } catch (Exception ex) {
            Logger.getLogger(CHITIETHOADON.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void AutomaticallyClosedMsgBox(long time, String text) {
        JOptionPane jop = new JOptionPane();
        jop.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        jop.setMessage(text);
        JDialog dialog = jop.createDialog(null, "Thông báo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablecthd = new javax.swing.JTable();
        jButtonsuacthd = new javax.swing.JButton();
        jButtonxoacthd = new javax.swing.JButton();
        jButtonthemcthd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldsl = new javax.swing.JTextField();
        jTextFieldgia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldmahd = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jComboBoxsach = new javax.swing.JComboBox<>();
        jTextFieldmacthd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHI TIẾT HÓA ĐƠN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jTablecthd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTablecthd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên sách", "Số lượng", "Giá "
            }
        ));
        jTablecthd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablecthdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablecthd);
        if (jTablecthd.getColumnModel().getColumnCount() > 0) {
            jTablecthd.getColumnModel().getColumn(1).setResizable(false);
        }

        jButtonsuacthd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonsuacthd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pencil-30.png"))); // NOI18N
        jButtonsuacthd.setText("SỬA");
        jButtonsuacthd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuacthdActionPerformed(evt);
            }
        });

        jButtonxoacthd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonxoacthd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-trash-can-30.png"))); // NOI18N
        jButtonxoacthd.setText("XÓA");
        jButtonxoacthd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxoacthdActionPerformed(evt);
            }
        });

        jButtonthemcthd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonthemcthd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-new-30.png"))); // NOI18N
        jButtonthemcthd.setText("THÊM");
        jButtonthemcthd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthemcthdActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Tên sách:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Số lượng:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Giá:");

        jTextFieldsl.setMinimumSize(new java.awt.Dimension(7, 28));
        jTextFieldsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldslActionPerformed(evt);
            }
        });

        jTextFieldgia.setMinimumSize(new java.awt.Dimension(7, 28));
        jTextFieldgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldgiaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Mã hóa đơn:");

        jTextFieldmahd.setMinimumSize(new java.awt.Dimension(7, 28));
        jTextFieldmahd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmahdActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-undo-40.png"))); // NOI18N
        jButton11.setText("QUAY LẠI");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jTextFieldmacthd.setMinimumSize(new java.awt.Dimension(7, 28));
        jTextFieldmacthd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmacthdActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Chi tiết hóa đơn:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldsl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(jTextFieldmahd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxsach, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldmacthd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton11)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonsuacthd, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonxoacthd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonthemcthd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonthemcthd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonsuacthd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonxoacthd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldmacthd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldmahd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxsach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldsl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldgia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonxoacthdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxoacthdActionPerformed
        // TODO add your handling code here:
        int macthd = Integer.parseInt(jTextFieldmacthd.getText());
        ctBUS.delete(macthd);
        CTHDBUS nvBUS = new CTHDBUS();
        try {
            AutomaticallyClosedMsgBox(1500, "Đang xóa.\nXin hãy đợi....");
            ThongBao.noitice("Xóa thành công");
           String mahd =jTextFieldmahd.getText();
            nvBUS.updateTable(jTablecthd, Integer.parseInt(mahd));
            jTablecthd.removeColumn(jTablecthd.getColumnModel().getColumn(1));
            jTablecthd.removeColumn(jTablecthd.getColumnModel().getColumn(0));
            jTextFieldmacthd.setText(null);
            jTextFieldsl.setText(null);
            jTextFieldgia.setText(null);
            jComboBoxsach.setSelectedIndex(0);

        } catch (Exception ex) {
            Logger.getLogger(EMPLOYEE.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonxoacthdActionPerformed

    private void jButtonthemcthdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthemcthdActionPerformed
        // TODO add your handling code here:
        if (jTextFieldmahd.getText().isEmpty()) {
            ThongBao.error("Mã hóa đơn không để trống");
        } else if (jTextFieldsl.getText().isEmpty())
            ThongBao.error("Số lượng  không để trống");
        else if (jTextFieldgia.getText().isEmpty())
            ThongBao.error("Giá không để trống");
        else {
            int mahd = Integer.parseInt(jTextFieldmahd.getText());
            int sl = Integer.parseInt(jTextFieldsl.getText());
            int gia = Integer.parseInt(jTextFieldgia.getText());
            int masach = eBUS.maSach[jComboBoxsach.getSelectedIndex()];
            BUS.CTHDBUS cthdBUS = new BUS.CTHDBUS();
            cthdBUS.add(mahd, masach, sl, gia);
            try {
                AutomaticallyClosedMsgBox(1500, "Đang thêm.\nXin hãy đợi....");
                ThongBao.noitice("Thêm thành công");
                ctBUS.updateTable(jTablecthd, mahd);
                jTablecthd.removeColumn(jTablecthd.getColumnModel().getColumn(1));
                jTablecthd.removeColumn(jTablecthd.getColumnModel().getColumn(0));
                jTextFieldmacthd.setText(null);
                jTextFieldsl.setText(null);
                jTextFieldgia.setText(null);
                jComboBoxsach.setSelectedIndex(0);

            } catch (Exception ex) {
                Logger.getLogger(EMPLOYEE.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonthemcthdActionPerformed

    private void jTextFieldslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldslActionPerformed

    private void jTextFieldgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldgiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldgiaActionPerformed

    private void jTextFieldmahdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmahdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldmahdActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        EMPLOYEE e = new EMPLOYEE();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTablecthdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablecthdMouseClicked
        // TODO
        jTextFieldmacthd.setText((jTablecthd.getModel().getValueAt(jTablecthd.getSelectedRow(), 0)).toString());
        jTextFieldmahd.setText((jTablecthd.getModel().getValueAt(jTablecthd.getSelectedRow(), 1)).toString());
        jComboBoxsach.setSelectedItem((jTablecthd.getModel().getValueAt(jTablecthd.getSelectedRow(), 2)).toString());
        jTextFieldsl.setText((jTablecthd.getModel().getValueAt(jTablecthd.getSelectedRow(), 3)).toString());
        jTextFieldgia.setText((jTablecthd.getModel().getValueAt(jTablecthd.getSelectedRow(), 4)).toString());
    }//GEN-LAST:event_jTablecthdMouseClicked

    private void jButtonsuacthdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuacthdActionPerformed
        // TODO add your handling code here:
        if (jTextFieldmahd.getText().isEmpty()) {
            ThongBao.error("Mã hóa đơn không để trống");
        } else if (jTextFieldsl.getText().isEmpty())
            ThongBao.error("Số lượng  không để trống");
        else if (jTextFieldgia.getText().isEmpty())
            ThongBao.error("Giá không để trống");
        else {
            int macthd = Integer.valueOf(jTextFieldmacthd.getText());
            int mahd = Integer.parseInt(jTextFieldmahd.getText());
            int sl = Integer.parseInt(jTextFieldsl.getText());
            int gia = Integer.parseInt(jTextFieldgia.getText());
            int masach = eBUS.maSach[jComboBoxsach.getSelectedIndex()];
            BUS.CTHDBUS cthdBUS = new BUS.CTHDBUS();
            cthdBUS.edit(macthd, mahd, masach, sl, gia);
            try {
                AutomaticallyClosedMsgBox(1500, "Đang sửa.\nXin hãy đợi....");
                ThongBao.noitice("Sửa thành công");
                ctBUS.updateTable(jTablecthd, mahd);
                jTablecthd.removeColumn(jTablecthd.getColumnModel().getColumn(1));
                jTablecthd.removeColumn(jTablecthd.getColumnModel().getColumn(0));
                jTextFieldmacthd.setText(null);
                jTextFieldsl.setText(null);
                jTextFieldgia.setText(null);
                jComboBoxsach.setSelectedIndex(0);

            } catch (Exception ex) {
                Logger.getLogger(EMPLOYEE.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonsuacthdActionPerformed

    private void jTextFieldmacthdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmacthdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldmacthdActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CHITIETHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CHITIETHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CHITIETHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CHITIETHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CHITIETHOADON().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButtonsuacthd;
    private javax.swing.JButton jButtonthemcthd;
    private javax.swing.JButton jButtonxoacthd;
    public static javax.swing.JComboBox<String> jComboBoxsach;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTablecthd;
    private javax.swing.JTextField jTextFieldgia;
    public static javax.swing.JTextField jTextFieldmacthd;
    public static javax.swing.JTextField jTextFieldmahd;
    private javax.swing.JTextField jTextFieldsl;
    // End of variables declaration//GEN-END:variables
}
